### PR TITLE
feat: add article editor embed media working

### LINKED ISSUE #235: Article editor, add support for embed media
* PR target branch: `feature/articles`

By default, if the url property is empty the block only shows an input with a placeholder "Youtube, Spotify url".

If a **valid** URL is entered, the block displays the embedded spotify / youtube iframe, with the input field still editable at the bottom of the block.

### PR DESCRIPTION
**Pull request by GemN**
require #245
fixes #235

### CODE REVIEW

**Comment by ciphrd** [comment]
Nice implementation.

Found a weird random bug:
https://user-images.githubusercontent.com/18054507/179045264-f2f26897-bf92-4ddc-8979-09ffcd38441a.mp4

It does only occur in some circumstances, I'll let you investigate

**Review by ciphrd — CHANGES_REQUESTED** [review]
Nice implementation.

Found a weird random bug:

https://user-images.githubusercontent.com/18054507/179045679-bc52bf12-19ed-4a51-9fc7-c7c33482357b.mp4

It does only occur in some circumstances, I'll let you investigate

**Comment by GemN** [comment]
Previous bug featured in the video was unrelated and fixed in another PR - it's fine now.
There is another bug when typing at the moment but this bug was introduced by an another feature, so unrelated at the moment

**Review by ciphrd — APPROVED** [review]
LGTM

**Pull request merged**
