### PR TITLE
✨ show next open time when mint is closed

### PR DESCRIPTION
**Pull request by percentcer**
When the mint is closed, display when it will be next open (in the top bar)

image

### CODE REVIEW

**Review by ciphrd — CHANGES_REQUESTED** [review]
It's a good feature, however this implementation does not provide the correct hour.

The environment variable OPENING_SCHEDULE_REFERENCE actually refers to a time of reference set in the past, from which are derived the cycle openings of the platform (the isPlatformOpened function is a good example).

So starting from OPENING_SCHEDULE_REFERENCE, there are cycles of 12 hours opening / 11 hours closing looping endlessly.

You would need to find the next time when the platform will open, based on the current time.

I would also suggest adding the timezone code along the date, as some people may have a local timezone not properly set to the timezone of their geographic position.

**Comment by percentcer** [comment]
Ah thanks for the info, let me take another stab at it! Do you mind posting your current `OPENING_SCHEDULE_REFERENCE` as well? I wasn't sure if I had set a reasonable value in my `.env.local`

**Comment by percentcer** [comment]
Updated commit to use proper cycle time calculations. Also added the timezone abbreviation and included the closing time information (when mint is already open)

image

**Comment by ciphrd** [comment]
Thanks for your work ! 
I ended up removing the timezone code because it was showing RDT for me (which is one hour off).
This is not related to your work but rather the timezone sources i'm using (the utc name is correct but the abbreviation isn't, which is really weird).

For reference this is the timezone in question:

```json
{
  "value": "Romance Standard Time",
  "abbr": "RDT",
  "offset": 2,
  "isdst": true,
  "text": "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
  "utc": [
    "Africa/Ceuta",
    "Europe/Brussels",
    "Europe/Copenhagen",
    "Europe/Madrid",
    "Europe/Paris"
  ]
},
```

RDT is hour off from UTC+1, which doesn't seem right... Needs more investigation, this whole timezone thing is had to track

**Pull request merged**
