### PR TITLE
change/MasonryCards

### PR DESCRIPTION
**Pull request by jbmoutout**
@ciphrd A very basic approach to Masonry (avoiding the mandatory `height` Flexbox caveat).
Would require an eventListener to update number of columns on window resize.

Screenshot 2022-04-22 at 16 38 27

### CODE REVIEW

**Comment by ciphrd** [comment]
Runtime error when running on the home page:

image


On the explore page (and all the other pages using the `CardsContainer` component), the cards are visually broken:

image


The implementation in itself is okay, but creating a new `MasonryCardsContainer` would have been more appropriate.

**Comment by jbmoutout** [comment]
Agreed,was only attempting to show a quick lead for futur implementation

**Comment by jbmoutout** [comment]
@ciphrd a bit more complete implementation example with dedicated component and resizing listener.

⚠️  issue between the CardLoading logic and masonry when replacing placeholder height (see loom) that would require more work. https://www.loom.com/share/19388a89e654497187473553e04a822b

**Comment by maerzhase** [comment]
we can close this one, i opened anohter PR based on it #153

**Pull request closed without merging**
